spring:
  security:
      user:
        name: admin
        password: hardPass
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
